# Dockerfile based on the latest CentOS 7 image - non-privileged user entry
FROM centos:latest
MAINTAINER kasra@caseraw.com

RUN useradd -ms /bin/bash user
USER user

--------------------------------------------------------------------------------

Build:
It can be build via with:
docker build -t centos7/nonroot:v1 .

Run with:
docker run -it centos7/nonroot:v1 /bin/bash

Explenation:

This will pull an image, with the specified parameters.
This will create a user called "user".
When running you will be logged in as "user".
Exiting will stop the container.

Logging in with root can be done by executing the following command on a running container:
docker exec -u 0 -it small_lamarr /bin/bash

This command will log in as root in order to make changes on the running conatiner.
Exiting will not stop the container, because it has a running bash proces from "user".

Notes:
Keep in mind that running the specific commands follow a specific priority.
You may run into permission errors if used improperly.
